In [17]:
import numpy as np
import pandas as pd
import glob, os, vcf, warnings, shutil, subprocess, re
from Bio import Seq, SeqIO
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
import scipy, pysam
import panel as pn
# pn.extension('ipywidgets')
# pn.extension()

h37Rv_path = "/n/data1/hms/dbmi/farhat/Sanjana/H37Rv"
h37Rv_seq = SeqIO.read(os.path.join(h37Rv_path, "GCF_000195955.2_ASM19595v2_genomic.gbff"), "genbank")
h37Rv_genes = pd.read_csv(os.path.join(h37Rv_path, "mycobrowser_h37rv_genes_v4.csv"))
h37Rv_regions = pd.read_csv(os.path.join(h37Rv_path, "mycobrowser_h37rv_v4.csv"))

h37Rv_coords = pd.read_csv(os.path.join(h37Rv_path, "h37Rv_coords_to_gene.csv"))
h37Rv_coords_dict = dict(zip(h37Rv_coords["pos"].values, h37Rv_coords["region"].values))

TRUST_data_dir = "~/TRUST_data_processing/processed_data"
df_trust_patients = pd.read_csv(f"{TRUST_data_dir}/combined_patient_WGS_data.csv").dropna(subset='Lineage')

isolate_variants = pd.read_csv("/n/data1/hms/dbmi/farhat/rollingDB/metadata/isolate_metadata.csv")

In [27]:
df_longitudinal_pids = pd.read_csv(f"{TRUST_data_dir}/longitudinal_pids_WGS_data.csv")

In [31]:
df_longitudinal_pids.query("pid in ['T0254', 'T0210']")

,pid,Original_ID,SampleID,Sampling_Week,screen_prevpid,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,F2,Lineage,Paired_Sample_Num,total_samples
274,T0210,S0210-01,MFS-638,1,NaN,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,0.008268,2,1,2
275,T0210,S0210-06,MFS-639,6,NaN,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,0.007451,2,2,2
332,T0254,S0254-01,MFS-169,1,T0210,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,0.009093,2,1,2
333,T0254,S0254-06,MFS-170,6,T0210,2.2.1.1,2.2.1.1.1,"beijing,canetti,mungi","lin2.2.1,pacific_RD150",NaN,0.008867,2,2,2

In [12]:
liftoff_gff = pd.read_csv("/n/data1/hms/dbmi/farhat/Sanjana/TRUST_aln_personal_assembly/MFS-1/assembly/H37Rv.liftoff.gff_polished", sep='\t', comment='#', header=None)
liftoff_gff['Length'] = liftoff_gff[4] - liftoff_gff[3] + 1

In [14]:
liftoff_gff.loc[liftoff_gff[8].str.contains('|'.join(['uspC', 'Rv2319c']))]

,0,1,2,3,4,5,6,7,8,Length
4695,S0004-01_contig_1_pilon,Liftoff,gene,2585916,2587238,.,+,.,ID=gene-Rv2318;Dbxref=GeneID:885143;Name=uspC;...,1323
4696,S0004-01_contig_1_pilon,Liftoff,CDS,2585916,2587238,.,+,.,ID=cds-NP_216834.1;Parent=gene-Rv2318;Dbxref=G...,1323
4697,S0004-01_contig_1_pilon,Liftoff,gene,2588198,2589076,.,-,.,ID=gene-Rv2319c;Dbxref=GeneID:885171;Name=Rv23...,879
4698,S0004-01_contig_1_pilon,Liftoff,CDS,2588198,2589076,.,-,.,ID=cds-NP_216835.1;Parent=gene-Rv2319c;Dbxref=...,879

In [29]:
df_Kevin = pd.read_csv("~/data_cleaning/data/biosamples_metadata_for_Kevin.csv")
df_Kevin[['BioSample_ID']].to_csv("~/data_cleaning/data/Kevin_samples.csv", header=None, index=False)#, 'Sample_Name']]#.merge(df_SRA.query("Platform=='ILLUMINA'")[['BioSample', 'Run']], left_on='BioSample_ID', right_on='BioSample')

df_Kevin_metadata = pd.read_csv("~/data_cleaning/data/Kevin_samples_metadata.csv")

# df_SRA = pd.read_csv("~/data_cleaning/data/SraRunTable.csv")

In [34]:
set(df_Kevin.BioSample_ID) - set(df_Kevin_metadata.dropna(subset='Run').Query)

set()

In [36]:
len(df_Kevin), len(df_Kevin_metadata)

(830, 830)

In [42]:
df_Kevin_run = df_Kevin_metadata[['BioSample', 'Run']]
df_Kevin_run['FQ'] = 1
df_Kevin_run.to_csv("~/Mtb_Megapipe/Kevin_samples_rerun.tsv", sep='\t', header=None, index=False)

df_Kevin_run.BioSample.nunique(), df_Kevin_run.Run.nunique()

(830, 830)

In [2]:
df_NYC_cases = pd.read_sas("~/transmission_lineages/raw_data/cases_052023.sas7bdat")
cases_specnum_mapping = pd.read_sas("~/transmission_lineages/raw_data/cases_specnum_mapping_052023.sas7bdat", encoding='utf-8')
contacts = pd.read_sas("~/transmission_lineages/raw_data/contacts_0623023.sas7bdat", encoding='utf-8')

In [3]:
cases_specnum_mapping['SAMPLEID'] = cases_specnum_mapping['SPECIMEN_NUMBER'].str.split('-').str[0]

In [4]:
len(cases_specnum_mapping), cases_specnum_mapping.SPECIMEN_NUMBER.nunique(), cases_specnum_mapping.SAMPLEID.nunique()

(3190, 3188, 3188)

In [5]:
cases_specnum_mapping.iloc[cases_specnum_mapping.index.values[cases_specnum_mapping.duplicated(subset='SAMPLEID', keep=False)]]

        CASE_ID   SPECIMEN_NUMBER       SAMPLEID
1285  201808067  IDR1800041896-01  IDR1800041896
1795  201909406  IDR1800041896-01  IDR1800041896
3188  202206771     IDR2200050648  IDR2200050648
3189  202203376     IDR2200050648  IDR2200050648

In [33]:
print(len(cases_specnum_mapping[['SAMPLEID']].drop_duplicates()))
cases_specnum_mapping[['SAMPLEID']].drop_duplicates().to_csv("~/data_cleaning/data/Matthias_newNYC_search.csv", index=False, header=None)

3188

In [6]:
df_metadata = pd.read_csv("~/data_cleaning/data/Matthias_newNYC_search_metadata.csv")#.drop_duplicates(subset=['RunHash', 'ReadHash'])

df_metadata.dropna(subset='Run').Query.nunique(), len(set(cases_specnum_mapping['SAMPLEID'].values) - set(df_metadata.dropna(subset='Run').Query))

(2042, 1146)

In [10]:
df_metadata.dropna(subset='Run').to_csv("~/data_cleaning/data/Matthias_newNYC_search_metadata.csv", index=False)

In [29]:
set(cases_specnum_mapping['SAMPLEID'].values[:10]) - set(df_metadata.dropna(subset='Run').Query)

{'IDR1600032256'}

In [84]:
IDR_sample_metadata = pd.read_csv("~/data_cleaning/data/IDR_sample_metadata.csv").drop_duplicates(subset='Run').reset_index(drop=True)
IDR_sample_metadata['Sample_noSpace'] = IDR_sample_metadata['SampleName'].str.replace(' ', '')
IDR_sample_metadata['Sample_noPrefix'] = IDR_sample_metadata['Sample_noSpace'].str.split('-').str[0]

len(IDR_sample_metadata), IDR_sample_metadata.Sample_noSpace.nunique(), IDR_sample_metadata.SampleName.nunique(), IDR_sample_metadata.BioSample.nunique(), IDR_sample_metadata.Run.nunique()

(5000, 4937, 4950, 4950, 5000)

In [89]:
IDR_sample_metadata.query("Sample_noSpace.str.contains('-')")[['BioSample', 'Run', 'SampleName', 'Sample_noSpace', 'Sample_noPrefix']].merge(cases_specnum_mapping, left_on='Sample_noSpace', right_on='SPECIMEN_NUMBER')

Empty DataFrame
Columns: [BioSample, Run, SampleName, Sample_noSpace, Sample_noPrefix, CASE_ID, SPECIMEN_NUMBER, SAMPLEID]
Index: []

In [90]:
IDR_sample_metadata.query("Sample_noSpace.str.contains('-')")[['BioSample', 'Run', 'SampleName', 'Sample_noSpace', 'Sample_noPrefix']].merge(cases_specnum_mapping, left_on='Sample_noPrefix', right_on='SAMPLEID')

,BioSample,Run,SampleName,Sample_noSpace,Sample_noPrefix,CASE_ID,SPECIMEN_NUMBER,SAMPLEID
0,SAMN40207957,SRR28170774,IDR1600021054-01-01,IDR1600021054-01-01,IDR1600021054,201602249,IDR1600021054-01,IDR1600021054
1,SAMN40207994,SRR28170800,IDR1600030328-01-02,IDR1600030328-01-02,IDR1600030328,201605016,IDR1600030328-01,IDR1600030328
2,SAMN40208006,SRR28170747,IDR1600037087-01-01,IDR1600037087-01-01,IDR1600037087,201605104,IDR1600037087-01,IDR1600037087
3,SAMN40208001,SRR28170742,IDR1600047580-01-01,IDR1600047580-01-01,IDR1600047580,201604566,IDR1600047580-01,IDR1600047580
4,SAMN40207964,SRR28170792,IDR1600048722-01-01,IDR1600048722-01-01,IDR1600048722,201606836,IDR1600048722-01,IDR1600048722
...,...,...,...,...,...,...,...,...
83,SAMN37480151,SRR26124829,IDR2200056295-01-02,IDR2200056295-01-02,IDR2200056295,202207159,IDR2200056295-01,IDR2200056295
84,SAMN37480152,SRR26124840,IDR2200058676-01-01,IDR2200058676-01-01,IDR2200058676,202207607,IDR2200058676-01,IDR2200058676
85,SAMN37480153,SRR26124839,IDR2200058676-01-02,IDR2200058676-01-02,IDR2200058676,202207607,IDR2200058676-01,IDR2200058676
86,SAMN37480154,SRR26124838,IDR2300001892-01-01,IDR2300001892-01-01,IDR2300001892,202207796,IDR2300001892-01,IDR2300001892
87,SAMN37480155,SRR26124837,IDR2300001892-01-02,IDR2300001892-01-02,IDR2300001892,202207796,IDR2300001892-01,IDR2300001892

In [92]:
IDR_sample_metadata[['BioSample', 'Run', 'SampleName', 'Sample_noSpace', 'Sample_noPrefix']].merge(cases_specnum_mapping, left_on='Sample_noPrefix', right_on='SAMPLEID')

,BioSample,Run,SampleName,Sample_noSpace,Sample_noPrefix,CASE_ID,SPECIMEN_NUMBER,SAMPLEID
0,SAMN32115348,SRR22577871,IDR 1700031832,IDR1700031832,IDR1700031832,201700976,IDR1700031832-01,IDR1700031832
1,SAMN31034614,SRR21722120,IDR 1800042629,IDR1800042629,IDR1800042629,201807481,IDR1800042629-01,IDR1800042629
2,SAMN31034615,SRR21722119,IDR 1800042631,IDR1800042631,IDR1800042631,201807105,IDR1800042631-01,IDR1800042631
3,SAMN31034616,SRR21722112,IDR 1800042632,IDR1800042632,IDR1800042632,201806446,IDR1800042632-01,IDR1800042632
4,SAMN31034617,SRR21722111,IDR 1800043382,IDR1800043382,IDR1800043382,201808183,IDR1800043382-01,IDR1800043382
...,...,...,...,...,...,...,...,...
1583,SAMN37458139,SRR26112723,IDR2300016849,IDR2300016849,IDR2300016849,202209202,IDR2300016849-01,IDR2300016849
1584,SAMN37458130,SRR26112583,IDR2300018414,IDR2300018414,IDR2300018414,202205339,IDR2300018414-01,IDR2300018414
1585,SAMN37458143,SRR26112790,IDR2300018415,IDR2300018415,IDR2300018415,202208522,IDR2300018415-01,IDR2300018415
1586,SAMN37458119,SRR26112780,IDR2300019646,IDR2300019646,IDR2300019646,202207750,IDR2300019646-01,IDR2300019646
1587,SAMN37458123,SRR26112569,IDR2300022587,IDR2300022587,IDR2300022587,202209349,IDR2300022587-01,IDR2300022587

In [83]:
IDR_sample_metadata.query("Sample.str.contains('IDR1600032256')")

Empty DataFrame
Columns: [Run, ReleaseDate, LoadDate, spots, bases, spots_with_mates, avgLength, size_MB, AssemblyName, download_path, Experiment, LibraryName, LibraryStrategy, LibrarySelection, LibrarySource, LibraryLayout, InsertSize, InsertDev, Platform, Model, SRAStudy, BioProject, Study_Pubmed_id, ProjectID, Sample, BioSample, SampleType, TaxID, ScientificName, SampleName, g1k_pop_code, source, g1k_analysis_group, Subject_ID, Sex, Disease, Tumor, Affection_Status, Analyte_Type, Histological_Type, Body_Site, CenterName, Submission, dbgap_study_accession, Consent, RunHash, ReadHash]
Index: []

[0 rows x 47 columns]

In [79]:
cases_specnum_mapping

        CASE_ID   SPECIMEN_NUMBER       SAMPLEID
0     201501309  IDR1600045100-01  IDR1600045100
1     201506928  IDR1600030701-01  IDR1600030701
2     201510242  IDR1600002328-01  IDR1600002328
3     201510299  IDR1600007943-01  IDR1600007943
4     201510336  IDR1600032256-01  IDR1600032256
...         ...               ...            ...
3185  201600722     IDR1600006610  IDR1600006610
3186  201600945     IDR1600006613  IDR1600006613
3187  202006873     IDR2100011033  IDR2100011033
3188  202206771     IDR2200050648  IDR2200050648
3189  202203376     IDR2200050648  IDR2200050648

[3190 rows x 3 columns]

In [67]:
IDR_sample_metadata[['BioSample', 'Run', 'SampleName', 'Sample']].merge(cases_specnum_mapping, left_on='Sample', right_on='SPECIMEN_NUMBER')

,BioSample,Run,SampleName,Sample,CASE_ID,SPECIMEN_NUMBER,SAMPLEID
0,SAMN31063384,SRR21737226,IDR2100011033,IDR2100011033,202006873,IDR2100011033,IDR2100011033
1,SAMN37458082,SRR26112440,IDR2200050648,IDR2200050648,202206771,IDR2200050648,IDR2200050648
2,SAMN37458082,SRR26112440,IDR2200050648,IDR2200050648,202203376,IDR2200050648,IDR2200050648

In [73]:
IDR_sample_metadata.query("Sample.str.contains('IDR2200050648')")[['BioSample', 'Run', 'SampleName', 'Sample']]

         BioSample          Run     SampleName         Sample
2351  SAMN37458082  SRR26112440  IDR2200050648  IDR2200050648

In [35]:
len() - set(IDR_sample_metadata.)

,Run,ReleaseDate,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,download_path,...,Affection_Status,Analyte_Type,Histological_Type,Body_Site,CenterName,Submission,dbgap_study_accession,Consent,RunHash,ReadHash
0,SRR22577871,2022-12-08 13:56:03,2022-12-08 13:52:47,1411469,678405667,1411469,480,395,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA1555785,NaN,public,4DC2645AFC045223FC4290590982240A,E4FBE5518A31F214D17CF25ECF5C5E2D
1,SRR21722120,2022-09-27 09:29:19,2022-09-27 09:27:30,567871,241978538,567871,426,144,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA1507825,NaN,public,48DC852364B2C0A0A7B5BCF9B5FE8C4C,697B9F6AD16F45FA4A918966D5550444
2,SRR21722119,2022-09-27 09:29:19,2022-09-27 09:28:37,1737737,831177326,1737737,478,539,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA1507825,NaN,public,140DF79030F6630DD83FCBA3FC120EDC,6FF527AD08F87D0AB106A3B34B6484DD
3,SRR21722112,2022-09-27 09:29:19,2022-09-27 09:27:54,1126597,539310417,1126597,478,327,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA1507825,NaN,public,8DB76FF455F9D1DA71767535E5C4D2E7,7E4D0178EA846755D1556724EEB99F95
4,SRR21722111,2022-09-27 09:29:19,2022-09-27 09:27:46,989884,471208806,989884,476,286,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA1507825,NaN,public,A9FD8C4E30168E5441672E56E1523A9A,62B8597CFF2168BC4E6A41DC26DC91DD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SRR35891514,2025-10-28 12:52:02,2025-10-28 12:29:14,1391886,408520681,1391886,293,166,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA2259754,NaN,public,986EB6AF61B275C4031BA5B3CE63059F,0E2C4C11433184C0B85AEA76DED8ED9C
9996,SRR35891512,2025-10-28 12:33:12,2025-10-28 11:59:03,753582,220854904,753582,293,89,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA2259754,NaN,public,7E61CF5A9358D5647D6E31792C7C459F,72DE8497A1F492FE5F8AE770C0712048
9997,SRR35891511,2025-10-28 12:33:12,2025-10-28 11:58:53,1265420,361422650,1265420,285,144,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA2259754,NaN,public,DE700094039D617D5D2FD826FACC0EE6,51ECAA64E7484D5341C9C5E3F7A4721B
9998,SRR35891510,2025-10-28 12:33:12,2025-10-28 11:59:04,1743498,507769109,1743498,291,203,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA2259754,NaN,public,CD4A4241EEA012B57890A381A7F5FFD3,19B6D1D7CFE3AD9140DFB4616334BA75
9999,SRR35891509,2025-10-28 12:33:12,2025-10-28 11:59:11,1591245,463568917,1591245,291,187,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,NaN,NaN,NaN,NaN,WADSWORTH CENTER,SRA2259754,NaN,public,B6AE416BE385510AAC5D7A9C2842611E,3551DB19E7E612FEAB4494645474BBFD

In [24]:
df_Matthias = pd.read_csv("/home/sak0914/Mtb_Megapipe/isolates_to_run_Matthias.tsv", sep='\t', header=None)
print(len(df_Matthias))

Matthias_dir = "/n/data1/hms/dbmi/farhat/mgroeschel/processed_samples"

5086

In [25]:
for i, row in df_Matthias.iterrows():
    
    sample = row[0]
    
    if os.path.isfile(f"{Matthias_dir}/{sample}/pilon/{sample}_full.vcf.gz") and os.path.isfile(f"{Matthias_dir}/{sample}/lineage/fast_lineage_caller_output.txt") and os.path.isfile(f"{Matthias_dir}/{sample}/lineage/F2_Coll2014.txt"):
        df_Matthias.loc[i, 'Done'] = 1

In [26]:
df_Matthias.Done.value_counts(dropna=False)

Done
1.0    5075
NaN      11
Name: count, dtype: int64

In [29]:
df_Matthias.query("Done != 1").iloc[:, :3][0].values

array(['SAMN31018851', 'SAMN30962896', 'SAMN27761765', 'SAMN27761658',
       'SAMEA104718871', 'SAMEA104718864', 'SAMEA104718784',
       'SAMEA104718764', 'SAMEA104718748', 'SAMEA104718442',
       'SAMEA104718421'], dtype=object)

In [7]:
df_Matthias.query("Done != 1").iloc[:, :3]#.to_csv("/home/sak0914/Mtb_Megapipe/SE_isolates_to_finish_Matthias.tsv", sep='\t', header=None, index=False)

                   0           1  2
1618  SAMEA104718871  ERR2446520  1
1625  SAMEA104718864  ERR2446513  1
1698  SAMEA104718784  ERR2446433  1
1717  SAMEA104718764  ERR2446413  1
1732  SAMEA104718748  ERR2446397  1
2010  SAMEA104718442  ERR2446091  1
2031  SAMEA104718421  ERR2446070  1

In [15]:
for sample in df_Matthias.query("Done != 1").iloc[:, :3][0].values:
    
    df_depth = pd.read_csv(f"{Matthias_dir}/{sample}/bam/{sample}.depth.tsv.gz", compression='gzip', sep='\t', header=None, names=['CHROM', 'POS', 'COV'])
    
    print(sample, df_depth.COV.median(), len(df_depth.query("COV >= 10")) / len(df_depth))

SAMEA104718871 11.0 0.6772440957019012
SAMEA104718864 1.0 0.0011367932953903542
SAMEA104718784 5.0 0.09317692810570115
SAMEA104718764 7.0 0.34845173966776166
SAMEA104718748 11.0 0.6068952917036531
SAMEA104718442 9.0 0.4003801853868452
SAMEA104718421 6.0 0.19044268521683624

In [4]:
df_TRUST_WGS = pd.read_csv("/n/data1/hms/dbmi/farhat/rollingDB/TRUST/Illumina_culture_WGS_summary.csv")
df_TOTAL_WGS = pd.read_csv("/n/data1/hms/dbmi/farhat/rollingDB/TOTAL/Illumina_culture_WGS_summary.csv")

len(df_TRUST_WGS), len(df_TOTAL_WGS)

(803, 65)

In [55]:
len(df_TRUST_WGS.query("F2 <= 0.03")) + len(df_TOTAL_WGS.query("F2 <= 0.03"))

804

In [56]:
df_TRUST_WGS.query("SampleID=='MFS-657'")

,SampleID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage,Freschi_Lineage_1,Freschi_Lineage_2,Culture_Mixed_Infection
542,MFS-657,0.49,331.303254,341.0,98.07126,97.931172,0.003258,4.3.4.2.1,4.2.1.2.1.1.i3.1,lam,NaN,4.3/LAM,4,4.2.1.2.1.1.i3.1,NaN,0

In [59]:
df_trust_WGS_metadata_merged.query("SampleID=='MFS-657'")

Empty DataFrame
Columns: [SampleID, SampleLib, Original_ID, Pacbio, Comment, quality, Cov Any Mean, Cov Unam Perc, Perc. Reads Mapped, Excluded, repeat_pcrfree_1, repeat_pcrfree_2, transfered_pcrfree, transfered_pacbio, Repeat_1_factor, repat_1_loading, Unnamed: 13, 250x, repeat_pacbio, repeat_pcrfree, shipment, status, comment, phylogenetic classification (Coll et al., 2014), patient_num, sample_week, pid, screen_version, screen_date, screen_ic, screen_icdate, screen_parentic___1, screen_icversion, screen_reenroll, screen_prevpid, screen_sex, screen_race, screen_alc, screen_age, screen_birthyr, screen_years, screen_ageest___1, screen_txinitiate, screen_tbpos, screen_comply, screen_ephx, screen_ephx_2, screen_preg, screen_pregtest___1, screen_pregdate, screen_prevtx_4mths, screen_eptb, screen_eptbloc, screen_rrtb, screen_hivtest, screen_hivdate, screen_prevtx, screen_hiv, screen_pkic, screen_pknoenroll, screen_pkicdate, screen_pkparentic___1, screen_final, screen_exclreas, screen_trust2, screen_trust1vs2, screen_paper, screen_staff, screen_crfdate, screen_verstaff, screen_verdate, screen_datastaff, screen_datadate, screening_complete, screen_version_add_additional_visit2, screen_version_add_additional_visit, screen_date_add_additional_visit2, screen_date_add_additional_visit, screen_ic_add_additional_visit2, screen_ic_add_additional_visit, screen_icdate_add_additional_visit2, screen_icdate_add_additional_visit, screen_parentic_add___1_additional_visit2, screen_parentic_add___1_additional_visit, screen_previd_add_additional_visit, screen_sex_add_additional_visit2, screen_sex_add_additional_visit, screen_race_add_additional_visit2, screen_race_add_additional_visit, screen_alc_add_additional_visit2, screen_alc_add_additional_visit, screen_age_add_additional_visit2, screen_age_add_additional_visit, screen_birthyr_add_additional_visit2, screen_birthyr_add_additional_visit, screen_years_add_additional_visit2, screen_years_add_additional_visit, screen_ageest_add___1_additional_visit2, screen_ageest_add___1_additional_visit, screen_txinitiate_add_additional_visit2, ...]
Index: []

[0 rows x 7887 columns]

In [57]:
df_redCap

,pid,screen_version,screen_date,screen_ic,screen_icdate,screen_parentic___1,screen_icversion,screen_reenroll,screen_prevpid,screen_sex,...,duration_of_use_cannabis,duration_of_use_meth,duration_of_use_mandrax,lca,fib4,prevtb_trt_time,TBtrt_diff_time,prevtb_age,prevtb_outcome,patient_num
0,T0001,13.0,2017-05-16,1,2017-05-16,0,3.2,NaN,NaN,1,...,NaN,NaN,NaN,1.0,4.353411,NaN,NaN,NaN,NaN,1
1,T0002,NaN,2017-05-18,1,2017-05-18,0,3.2,NaN,NaN,2,...,2.0,1.0,1.0,1.0,0.382609,NaN,NaN,NaN,NaN,2
2,T0003,NaN,2017-05-19,1,2017-05-19,0,3.2,NaN,NaN,2,...,NaN,NaN,NaN,3.0,0.844297,NaN,NaN,NaN,NaN,3
3,T0004,NaN,2017-05-23,1,2017-05-23,0,3.2,NaN,NaN,1,...,NaN,NaN,NaN,2.0,0.796894,NaN,NaN,NaN,1.0,4
4,T0005,NaN,2017-06-06,1,2017-06-06,0,NaN,NaN,NaN,1,...,18.0,12.0,NaN,1.0,0.324504,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,T0472,14.0,2024-03-06,1,2024-03-06,0,8.4,0.0,NaN,1,...,NaN,NaN,NaN,2.0,0.834031,NaN,NaN,NaN,1.0,472
454,T0474,14.0,2024-03-14,1,2024-03-14,0,8.4,0.0,NaN,1,...,2.0,NaN,NaN,2.0,0.345312,NaN,NaN,NaN,NaN,474
455,T0475,14.0,2024-03-15,1,2024-03-15,0,8.4,0.0,NaN,1,...,25.0,25.0,25.0,1.0,0.750000,NaN,NaN,NaN,NaN,475
456,T0476,14.0,2024-03-18,1,2024-03-18,0,8.4,0.0,NaN,1,...,NaN,NaN,NaN,2.0,0.994587,NaN,NaN,NaN,NaN,476
457,T0477,14.0,2024-03-19,1,2024-03-19,0,8.4,0.0,NaN,2,...,NaN,NaN,NaN,NaN,0.172926,NaN,NaN,NaN,NaN,477

In [15]:
df_redCap = pd.read_csv("/n/data1/hms/dbmi/farhat/rollingDB/TRUST/clinical_data/TRUST_DATA_2025-05-12_1129.cleaned.wide.csv")

# get the patient number to match WGS IDs and pids
df_redCap["patient_num"] = [int(patient_id.replace("T0", "")) for patient_id in df_redCap["pid"].values]

In [22]:
# get all Excel files from this directory
trust_report_fNames = glob.glob(f"/n/data1/hms/dbmi/farhat/rollingDB/TRUST/WGS_metadata_reports/*.xlsx")
print(f"{len(trust_report_fNames)} WGS metadata Excel files")

df_trust_WGS_metadata = []

# sort chronologically because below, we preferentially keep the later one
for fName in np.sort(trust_report_fNames)[::-1]:

    # read in single Excel file
    df = pd.read_excel(fName, sheet_name=None)

    # remove spaces from column name to make querying easier. Also there could be NaN rows if there are additional empty rows in the Excel sheet, so drop them
    df = df['summary'].rename(columns={'original ID': 'Original_ID'}).dropna(axis=0, how='all')

    # append to list for concatenation
    df_trust_WGS_metadata.append(df)

# the Excel files above are running totals, so the most recent file has data that is also in the older files. So drop duplicates, keeping the most recent (last) one
df_trust_WGS_metadata = pd.concat(df_trust_WGS_metadata).drop_duplicates('SampleID', keep='last')

df_trust_WGS_metadata = df_trust_WGS_metadata.reset_index(drop=True)

6 WGS metadata Excel files

In [96]:
print(f"{len(df_redCap.patient_num.unique())} patients in RedCap dataframe")

# each sample ID is in the format like 260-04, S0299-01, or S0271-01A. So use re to remove all alpha characters and keep only numbers.
# first number is the patient number, second is the sample number
# merge the patient number extracted from each sample with the patient numbers in df_trust_patient_data
for i, row in df_trust_WGS_metadata.iterrows():
    try:
        patient_num = int(re.findall(r'\d+', row["Original_ID"].split("-")[0])[0])
    # weird names like T-7, T-5, and P-T- 1
    except:
        patient_num = row["Original_ID"]

    try:
        sample_week = int(re.findall(r'\d+', row["Original_ID"].split("-")[1])[0])
    # weird names like T-7, T-5, and P-T- 1
    except:
        sample_week = row['Original_ID']

    df_trust_WGS_metadata.loc[i, ['patient_num', 'sample_week']] = [patient_num, sample_week]

# WGS_metadata["patient_num"] = [int(re.findall(r'\d+', val.split("-")[0])[0]) for val in WGS_metadata["Original_ID"].values]
# WGS_metadata["sample_week"] = [int(re.findall(r'\d+', val.split("-")[1])[0]) for val in WGS_metadata["Original_ID"].values]

# keep only samples for the patients in df_trust_patient_data
df_trust_WGS_metadata_merged = df_trust_WGS_metadata.merge(df_redCap, on="patient_num", how="inner")
print(f"Found {df_trust_WGS_metadata_merged.patient_num.nunique()}/{df_redCap.patient_num.nunique()} patients in the WGS metadata files")

contam_samples = df_TRUST_WGS.loc[pd.isnull(df_TRUST_WGS['Lineage'])].SampleID.values
print(len(contam_samples))

# keep only samples that we have FASTQs for
df_trust_WGS_metadata_merged = df_trust_WGS_metadata_merged.merge(df_TRUST_WGS, on='SampleID').reset_index(drop=True)

458 patients in RedCap dataframe
Found 426/458 patients in the WGS metadata files
29

In [219]:
df_trust_WGS_metadata_merged.pid.nunique()

424

In [222]:
df_trust_WGS_metadata_merged.dropna(subset='F2').pid.nunique()

424

In [228]:
df_send['Lineage']

0      2
1      2
2      2
3      2
4      2
      ..
832    4
833    4
834    2
835    2
836    4
Name: Lineage, Length: 837, dtype: object

In [229]:
df_send.Lineage.unique()

array(['2', '4', '3', '1', '2,3', '2,4', 2, 4, 1, 3], dtype=object)

In [230]:
df_send

,pid,SampleID,Original_ID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage,Study
0,T0099,MFS-872,S0099-08,0.30,424.791575,437.0,98.729466,98.598673,0.010216,2.2.1,2.2.1.1.1,"beijing,mungi",lin2.2.1,NaN,2,TRUST
1,T0099,MFS-871,S0099-06,0.33,408.984696,420.0,98.753653,98.601574,0.010294,2.2.1,2.2.1.1.1,"beijing,canetti,mungi",lin2.2.1,NaN,2,TRUST
2,T0099,MFS-738,S0099-01,0.36,289.864832,296.0,98.781013,98.637593,0.011482,2.2.1,2.2.1.1.1,beijing,lin2.2.1,NaN,2,TRUST
3,T0397,MFS-885,S0397-04,0.37,389.867762,399.0,98.617963,98.487306,0.010204,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TRUST
4,T0397,MFS-672,S0397-01,0.78,273.238905,280.0,98.589016,98.427893,0.011419,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TRUST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,CT000301,CT000301,CT000301,0.20,139.091373,144.0,98.663798,98.399649,0.007604,4.3.3,4.2.1.2.1.1.i4.1,lam,NaN,4.3/LAM,4,TOTAL
833,P000101,P000101,P000101,0.33,147.694045,152.0,98.989693,98.682090,0.385730,"4.3.2.1,2.2.1.1","2.2.1.1.1,4.2.1.2.1.1.i1","beijing,lam,canetti,mungi","lin2.2.1,pacific_RD150",4.3/LAM,4,TOTAL
834,P014001,P014001,P014001,0.33,1231.240137,1261.0,98.619663,98.553065,0.013445,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TOTAL
835,P038001,P038001,P038001,0.32,1307.617495,1338.0,98.620570,98.540711,0.010878,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TOTAL
836,P040301,P040301,P040301,0.31,1113.040281,1144.0,98.046937,97.992511,0.007134,4.3.4.2.1,4.2.1.2.1.1.i3.1,lam,NaN,4.3/LAM,4,TOTAL

In [221]:
df_trust_WGS_metadata_merged.loc[pd.isnull(df_trust_WGS_metadata_merged['F2'])]

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage,Freschi_Lineage_1,Freschi_Lineage_2,Culture_Mixed_Infection
20,MFS-183,MFS-183_lib48363,264-07,NaN,NaN,1,186.2,0.97,0.6105,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23,MFS-78,MFS-78_lib47065,157-01,NaN,NaN,3,147.41,0.7,0.4469,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
30,MFS-304,MFS-304_lib52345,S0287-06,NaN,NaN,1,153.13,0.99,0.4615,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
70,MFS-179,MFS-179_lib48359,260-04,NaN,NaN,4,6.65,0.0,0.0916,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
130,MFS-422,MFS-422_lib59429,S0344-01,NaN,NaN,4.0,37.95,0.01,0.2931,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
133,MFS-423,MFS-423_lib59430,S0345-01,NaN,NaN,1.0,156.4,0.99,0.5518,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
137,MFS-425,MFS-425_lib59432,S0346-01,NaN,NaN,4.0,14.72,0.0,0.224,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
141,MFS-451,MFS-451_lib59650,S0364-07,NaN,NaN,4.0,10.26,0.0,0.208,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
144,MFS-453,MFS-453_lib59652,S0365-08,NaN,NaN,4.0,8.75,0.01,0.0421,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
150,MFS-477,MFS-477_lib59745,S0382-05,NaN,NaN,4.0,5.33,0.0,0.0304,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [209]:
df_no_pids = df_trust_WGS_metadata.query("SampleID not in @df_trust_WGS_metadata_merged.SampleID").dropna(subset='Original_ID').reset_index(drop=True)

search_weird_IDs = df_no_pids.loc[(~pd.isnull(df_no_pids['Original_ID'])) & (df_no_pids['Original_ID'].str.contains('CT'))].Original_ID.values

In [216]:
search_weird_IDs

array(['CT2010-00401', 'CT2022-00892', 'CT2006-01067', 'CT2022-00891',
       'CT2011-01333', 'CT2023-01147', 'CT2013-00687', 'CT2010-01938',
       'CT2013-02348'], dtype=object)

In [213]:
df_TOTAL_WGS.query("SampleID.str.contains('|'.join(@search_weird_IDs))")

Empty DataFrame
Columns: [pid, SampleID, Kraken_Unclassified_Percent, Mean_Depth, Median_Depth, Perc_Sites_20x, Perc_Sites_10x, Coll2014, Freschi2020, Lipworth2019, Shitikov2017, Stucki2016, F2, Lineage, Original_ID, Study]
Index: []

In [215]:
df_no_pids.loc[(~pd.isnull(df_no_pids['Original_ID'])) & (df_no_pids['Original_ID'].str.contains('CT'))]

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,Unnamed: 13,250x,repeat_pacbio,repeat_pcrfree,shipment,status,comment,"phylogenetic classification (Coll et al., 2014)",patient_num,sample_week
1,MFS-896,MFS-896_lib83851,CT2010-00401,NaN,NaN,1,374.35,1,0.9829,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,401
2,MFS-902,MFS-902_lib84049,CT2022-00892,NaN,NaN,1,355.09,1,0.9759,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,892
5,MFS-895,MFS-895_lib83850,CT2006-01067,NaN,NaN,1,284.01,1,0.9821,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006,1067
7,MFS-901,MFS-901_lib83856,CT2022-00891,NaN,NaN,1,274.01,1,0.985,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,891
10,MFS-898,MFS-898_lib83853,CT2011-01333,NaN,NaN,1,267.23,0.99,0.9865,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,1333
12,MFS-903,MFS-903_lib84050,CT2023-01147,NaN,NaN,1,257.73,1,0.9699,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,1147
13,MFS-899,MFS-899_lib83854,CT2013-00687,NaN,NaN,1,250.48,1,0.9867,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,687
16,MFS-897,MFS-897_lib84076,CT2010-01938,NaN,NaN,1,288.5,1,0.982,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,1938
17,MFS-900,MFS-900_lib83855,CT2013-02348,NaN,NaN,1,286,0.99,0.987,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,2348

In [191]:
df_TRUST_send = df_trust_WGS_metadata_merged[['pid', 'SampleID', 'Original_ID', 'Kraken_Unclassified_Percent', 'Mean_Depth', 'Median_Depth',
       'Perc_Sites_10x', 'Perc_Sites_20x', 'F2', 'Coll2014', 'Freschi2020',
       'Lipworth2019', 'Shitikov2017', 'Stucki2016', 'Lineage']].dropna(subset='Lineage').reset_index(drop=True)

for i, row in df_TRUST_send.iterrows():
    if not row['Original_ID'].startswith('S'):
        
        length_numerical = len(row['Original_ID'].split('-')[0])
            
        newID = 'S' + '0' * (4 - length_numerical) + row['Original_ID']
        df_TRUST_send.loc[i, 'Original_ID'] = newID
        
samples_check_multiple_lineages = pd.DataFrame(df_TRUST_send.query("F2 <= 0.03").groupby('Original_ID').Coll2014.nunique()).query("Coll2014 > 1").index.values

for original_ID in samples_check_multiple_lineages:
    
    major_lineage = df_TRUST_send.query("Original_ID == @original_ID").Coll2014.mode().values[0]
    
    exclude_WGS_samples = df_TRUST_send.query("Original_ID == @original_ID & Coll2014 != @major_lineage").SampleID.values
    
print(f"Excluding {len(exclude_WGS_samples)} samples with discrepant lineages")

df_TRUST_send = df_TRUST_send.query("SampleID not in @exclude_WGS_samples").reset_index(drop=True)

df_TOTAL_WGS['Original_ID'] = df_TOTAL_WGS['SampleID']

df_TRUST_send['Study'] = 'TRUST'
df_TOTAL_WGS['Study'] = 'TOTAL'

df_send = pd.concat([df_TRUST_send, df_TOTAL_WGS]).reset_index(drop=True)

Excluding 1 samples with discrepant lineages

In [217]:
df_send.loc[pd.isnull(df_send['Lineage'])]

Empty DataFrame
Columns: [pid, SampleID, Original_ID, Kraken_Unclassified_Percent, Mean_Depth, Median_Depth, Perc_Sites_10x, Perc_Sites_20x, F2, Coll2014, Freschi2020, Lipworth2019, Shitikov2017, Stucki2016, Lineage, Study]
Index: []

In [193]:
df_send.query("F2 <= 0.03")

,pid,SampleID,Original_ID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage,Study
0,T0099,MFS-872,S0099-08,0.30,424.791575,437.0,98.729466,98.598673,0.010216,2.2.1,2.2.1.1.1,"beijing,mungi",lin2.2.1,NaN,2,TRUST
1,T0099,MFS-871,S0099-06,0.33,408.984696,420.0,98.753653,98.601574,0.010294,2.2.1,2.2.1.1.1,"beijing,canetti,mungi",lin2.2.1,NaN,2,TRUST
2,T0099,MFS-738,S0099-01,0.36,289.864832,296.0,98.781013,98.637593,0.011482,2.2.1,2.2.1.1.1,beijing,lin2.2.1,NaN,2,TRUST
3,T0397,MFS-885,S0397-04,0.37,389.867762,399.0,98.617963,98.487306,0.010204,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TRUST
4,T0397,MFS-672,S0397-01,0.78,273.238905,280.0,98.589016,98.427893,0.011419,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TRUST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,CT000101,CT000101,CT000101,0.25,133.731948,139.0,97.827693,97.574856,0.005499,4.3.4.2.1,4.2.1.2.1.1.i3.1,lam,NaN,4.3/LAM,4,TOTAL
832,CT000301,CT000301,CT000301,0.20,139.091373,144.0,98.663798,98.399649,0.007604,4.3.3,4.2.1.2.1.1.i4.1,lam,NaN,4.3/LAM,4,TOTAL
834,P014001,P014001,P014001,0.33,1231.240137,1261.0,98.619663,98.553065,0.013445,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TOTAL
835,P038001,P038001,P038001,0.32,1307.617495,1338.0,98.620570,98.540711,0.010878,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2,TOTAL
836,P040301,P040301,P040301,0.31,1113.040281,1144.0,98.046937,97.992511,0.007134,4.3.4.2.1,4.2.1.2.1.1.i3.1,lam,NaN,4.3/LAM,4,TOTAL

In [194]:
df_send.pid.nunique()

489

In [195]:
df_send.Study.value_counts()

Study
TRUST    772
TOTAL     65
Name: count, dtype: int64

In [179]:
df_send.to_csv("~/20251103_TRUST_TOTAL_WGS_combined.csv", index=False)

In [197]:
df_send.groupby('Study').pid.nunique()

Study
TOTAL     65
TRUST    424
Name: pid, dtype: int64

In [154]:
samples_check_multiple_lineages

array(['S0402-01'], dtype=object)

In [157]:
df_TRUST_send.query("Original_ID in @samples_check_multiple_lineages")

,pid,SampleID,Original_ID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage
9,T0402,MFS-886,S0402-01,0.38,340.830557,350.0,98.586001,98.457633,0.010952,2.2.1.1,2.2.1.1.1,"beijing,canetti,mungi","lin2.2.1,pacific_RD150",NaN,2
11,T0402,MFS-676,S0402-01,0.63,327.179331,335.0,98.615719,98.467312,0.009952,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2

In [159]:
df_TRUST_send.pid.nunique()

424

In [161]:
df_TRUST_send.F2.max()

0.4772970970697756

In [162]:
df_TRUST_send

,pid,SampleID,Original_ID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage
0,T0099,MFS-872,S0099-08,0.30,424.791575,437.0,98.729466,98.598673,0.010216,2.2.1,2.2.1.1.1,"beijing,mungi",lin2.2.1,NaN,2
1,T0099,MFS-871,S0099-06,0.33,408.984696,420.0,98.753653,98.601574,0.010294,2.2.1,2.2.1.1.1,"beijing,canetti,mungi",lin2.2.1,NaN,2
2,T0099,MFS-738,S0099-01,0.36,289.864832,296.0,98.781013,98.637593,0.011482,2.2.1,2.2.1.1.1,beijing,lin2.2.1,NaN,2
3,T0397,MFS-885,S0397-04,0.37,389.867762,399.0,98.617963,98.487306,0.010204,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2
4,T0397,MFS-672,S0397-01,0.78,273.238905,280.0,98.589016,98.427893,0.011419,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,T0297,MFS-285,S0297-01,0.64,309.748345,317.0,98.302472,98.161410,0.013954,4.3.4.1,4.2.1.2.1.1.i3.2,lam,NaN,4.3/LAM,4
768,T0290,MFS-264,S0290-01,0.66,267.095757,274.0,98.551320,98.381832,0.013014,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2
769,T0290,MFS-266,S0290-08,0.65,258.598158,266.0,98.537651,98.360071,0.012428,2.2.1.1,2.2.1.1.1,"beijing,mungi","lin2.2.1,pacific_RD150",NaN,2
770,T0312,MFS-290,S0312-05,0.44,259.017050,263.0,99.087528,98.925090,0.013378,3,3.1.1,"east_african_indian,ghana,mungi",NaN,NaN,3
771,T0312,MFS-289,S0312-01,0.48,320.662031,326.0,99.133838,98.995632,0.011808,3,3.1.1,"east_african_indian,ghana,mungi",NaN,NaN,3

In [98]:
df_trust_WGS_metadata_merged.pid.nunique(), df_trust_WGS_metadata_merged.SampleID.nunique(), len(df_trust_WGS_metadata_merged), df_trust_WGS_metadata_merged.Original_ID.nunique()

(424, 783, 783, 773)

In [90]:
df_trust_WGS_metadata_merged.query("")

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,dudit_frequency_baseline,duration_of_use_cannabis,duration_of_use_meth,duration_of_use_mandrax,lca,fib4,prevtb_trt_time,TBtrt_diff_time,prevtb_age,prevtb_outcome
0,MFS-872,MFS-872_lib83827,S0099-08,NaN,NaN,1,437,0.99,0.9851,0,...,Abstainers,41.0,1.0,24.0,1.0,0.638285,NaN,NaN,NaN,NaN
1,MFS-871,MFS-871_lib83826,S0099-06,NaN,NaN,1,420.73,0.99,0.9848,0,...,Abstainers,41.0,1.0,24.0,1.0,0.638285,NaN,NaN,NaN,NaN
2,MFS-738,MFS-738_lib72901,S0099-01,NaN,NaN,1.0,298.11,0.99,0.9883,0.0,...,Abstainers,41.0,1.0,24.0,1.0,0.638285,NaN,NaN,NaN,NaN
3,MFS-885,MFS-885_lib83840,S0397-04,NaN,NaN,1,401.05,0.99,0.9856,0,...,Abstainers,NaN,17.0,23.0,1.0,0.173819,NaN,NaN,NaN,3.0
4,MFS-672,MFS-672_lib66545,S0397-01,NaN,NaN,1,280.09,0.99,0.9829,0,...,Abstainers,NaN,17.0,23.0,1.0,0.173819,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,MFS-285,MFS-285_lib52226,S0297-01,NaN,NaN,1,233.53,0.99,0.99,NaN,...,NaN,NaN,NaN,NaN,2.0,0.214408,NaN,NaN,NaN,NaN
779,MFS-264,MFS-264_lib51734,S0290-01,NaN,NaN,1,266.25,0.99,0.9887,NaN,...,Abstainers,17.0,17.0,17.0,1.0,0.244969,NaN,NaN,NaN,2.0
780,MFS-266,MFS-266_lib51736,S0290-08,NaN,NaN,1,257.83,0.99,0.9869,NaN,...,Abstainers,17.0,17.0,17.0,1.0,0.244969,NaN,NaN,NaN,2.0
781,MFS-290,MFS-290_lib52231,S0312-05,NaN,NaN,1,256.25,1.0,0.991,NaN,...,NaN,NaN,NaN,NaN,3.0,0.516398,NaN,NaN,NaN,NaN
782,MFS-289,MFS-289_lib52230,S0312-01,NaN,NaN,1,240.45,1.0,0.9902,NaN,...,NaN,NaN,NaN,NaN,3.0,0.516398,NaN,NaN,NaN,NaN

In [93]:
df_trust_WGS_metadata_merged.query("pid=='T0157'")

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,dudit_frequency_baseline,duration_of_use_cannabis,duration_of_use_meth,duration_of_use_mandrax,lca,fib4,prevtb_trt_time,TBtrt_diff_time,prevtb_age,prevtb_outcome
22,MFS-876,MFS-876_lib83831,S0157-01,NaN,NaN,1,314.82,1,0.961,0,...,Abstainers,32.0,18.0,32.0,2.0,1.237429,NaN,NaN,NaN,3.0
23,MFS-78,MFS-78_lib47065,157-01,NaN,NaN,3,147.41,0.7,0.4469,NaN,...,Abstainers,32.0,18.0,32.0,2.0,1.237429,NaN,NaN,NaN,3.0
24,MFS-79,MFS-79_lib47066,157-06,NaN,NaN,1,436.64,1.0,0.9849,NaN,...,Abstainers,32.0,18.0,32.0,2.0,1.237429,NaN,NaN,NaN,3.0

In [91]:
df_trust_WGS_metadata_merged.query("pid=='T0114'")

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,dudit_frequency_baseline,duration_of_use_cannabis,duration_of_use_meth,duration_of_use_mandrax,lca,fib4,prevtb_trt_time,TBtrt_diff_time,prevtb_age,prevtb_outcome
5,MFS-873,MFS-873_lib83828,S0114-04,NaN,NaN,1,365.38,1,0.9859,0,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
6,MFS-742,MFS-742_lib72905,S0114-04,NaN,NaN,1.0,321.11,1.0,0.9869,0.0,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
7,MFS-364,MFS-364_lib59185,S0114-01,NaN,NaN,1.0,254.42,1.0,0.9895,NaN,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
8,MFS-365,MFS-365_lib59186,S0114-04,NaN,NaN,1.0,217.44,1.0,0.9894,NaN,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN

In [82]:
df_TRUST_WGS.query("SampleID in ['MFS-365', 'MFS-742']")

,SampleID,Kraken_Unclassified_Percent,Mean_Depth,Median_Depth,Perc_Sites_10x,Perc_Sites_20x,F2,Coll2014,Freschi2020,Lipworth2019,Shitikov2017,Stucki2016,Lineage,Freschi_Lineage_1,Freschi_Lineage_2,Culture_Mixed_Infection
231,MFS-365,0.39,286.754800,292.0,99.021859,98.896188,0.009635,4.3.2.1,4.2.1.2.1.1.i1,lam,NaN,4.3/LAM,4,4.2.1.2.1.1.i1,NaN,0
632,MFS-742,0.37,310.750915,316.0,99.521708,99.422695,0.140563,4.8,4.2.1.1.1.1.1.1.i1,canetti,NaN,4.10/PGG3,4,4.2.1.1.1.1.1.1.i1,NaN,0

In [85]:
df_trust_WGS_metadata_merged.query("pid=='T0114'")#[['Lineage']]

,SampleID,SampleLib,Original_ID,Pacbio,Comment,quality,Cov Any Mean,Cov Unam Perc,Perc. Reads Mapped,Excluded,...,dudit_frequency_baseline,duration_of_use_cannabis,duration_of_use_meth,duration_of_use_mandrax,lca,fib4,prevtb_trt_time,TBtrt_diff_time,prevtb_age,prevtb_outcome
7,MFS-873,MFS-873_lib83828,S0114-04,NaN,NaN,1,365.38,1,0.9859,0,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
8,MFS-742,MFS-742_lib72905,S0114-04,NaN,NaN,1.0,321.11,1.0,0.9869,0.0,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
9,MFS-364,MFS-364_lib59185,S0114-01,NaN,NaN,1.0,254.42,1.0,0.9895,NaN,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN
10,MFS-365,MFS-365_lib59186,S0114-04,NaN,NaN,1.0,217.44,1.0,0.9894,NaN,...,NaN,NaN,NaN,NaN,2.0,0.282037,NaN,NaN,NaN,NaN

In [33]:
samples_no_pid = list(set(df_trust_WGS_metadata.SampleID) - set(df_trust_WGS_metadata_merged.SampleID))
len(samples_no_pid)

38

In [7]:
liftoff_files = glob.glob(f"{personal_ref_dir}/*/assembly/H37Rv.liftoff.gff_polished")
print(len(liftoff_files))

H37Rv_gff = pd.read_csv("./lowAF_variant_calling/references/ref_genome/H37Rv.NCBI.gff3",
                           sep='\t',
                           header=None,
                           comment='#',
                           names = ['Chromosome', 'Source', 'FeatureType', 'Start', 'End', 'Score', 'Sense', 'Phase', 'Attributes']
                          ).query("FeatureType=='gene'").reset_index(drop=True)

H37Rv_gff['Length'] = H37Rv_gff['End'] - H37Rv_gff['Start'] + 1

df_genes_not_transformed = pd.DataFrame(columns = ['Sample', 'Num_Genes']).set_index('Sample')

for fName in liftoff_files:
    
    # sample = 'MFS-38'

    liftoff_gff = pd.read_csv(fName,
                               sep='\t',
                               header=None,
                               comment='#',
                               names = ['Chromosome', 'Source', 'FeatureType', 'Start', 'End', 'Score', 'Sense', 'Phase', 'Attributes']
                              ).query("FeatureType=='gene'").reset_index(drop=True)

    liftoff_gff['Length'] = liftoff_gff['End'] - liftoff_gff['Start'] + 1

    def get_RvID_from_gff(attr_str):
        """
        Parse the attributes column of a GFF line.
        Returns a dict of key:value pairs.
        """
        attributes = {}
        for item in attr_str.strip().split(";"):
            if item:
                key, value = item.strip().split("=", 1)
                attributes[key] = value

        return attributes['ID'].split('-')[-1]


    def get_geneName_from_gff(attr_str):

        attributes = {}
        for item in attr_str.strip().split(";"):
            if item:
                key, value = item.strip().split("=", 1)
                attributes[key] = value

        return attributes['Name']


    H37Rv_gff['RvID'] = H37Rv_gff['Attributes'].apply(lambda x: get_RvID_from_gff(x))
    H37Rv_gff['GeneName'] = H37Rv_gff['Attributes'].apply(lambda x: get_geneName_from_gff(x))

    liftoff_gff['RvID'] = liftoff_gff['Attributes'].apply(lambda x: get_RvID_from_gff(x))
    liftoff_gff['GeneName'] = liftoff_gff['Attributes'].apply(lambda x: get_geneName_from_gff(x))

    missing_genes = list(set(H37Rv_gff.GeneName) - set(liftoff_gff.GeneName))
    
    df_genes_not_transformed.loc[os.path.basename(os.path.dirname(os.path.dirname(fName))), :] = [len(missing_genes)]

94

In [107]:
df_BDQ = pd.read_csv("/n/data1/hms/dbmi/farhat/Sanjana/MIC_data/single_drugs/BDQ/data_for_model.csv")

In [109]:
df_BDQ.DB_OF_ORIGIN.value_counts()

DB_OF_ORIGIN
CRyPTIC        8558
NICD            315
WHO_catalog     131
Gandhi           74
Kreiswirth       60
Name: count, dtype: int64

In [110]:
315+134

449

In [10]:
df_genes_not_transformed.loc['MFS-37']

Num_Genes    28
Name: MFS-37, dtype: object

In [11]:
df_genes_not_transformed.loc['MFS-38']

Num_Genes    29
Name: MFS-38, dtype: object

In [46]:
df_genes_not_transformed.sort_values('Num_Genes')

        Num_Genes
Sample
MFS-135         6
MFS-5           6
MFS-56          7
MFS-104         8
MFS-105         8
...           ...
MFS-173        35
MFS-22         35
MFS-320        35
MFS-132        35
MFS-199        44

[94 rows x 1 columns]

In [42]:
sample = 'MFS-37'
fName = f"{personal_ref_dir}/{sample}/assembly/H37Rv.liftoff.gff_polished"

liftoff_gff = pd.read_csv(fName,
                           sep='\t',
                           header=None,
                           comment='#',
                           names = ['Chromosome', 'Source', 'FeatureType', 'Start', 'End', 'Score', 'Sense', 'Phase', 'Attributes']
                          ).query("FeatureType=='gene'").reset_index(drop=True)


liftoff_gff['RvID'] = liftoff_gff['Attributes'].apply(lambda x: get_RvID_from_gff(x))
liftoff_gff['GeneName'] = liftoff_gff['Attributes'].apply(lambda x: get_geneName_from_gff(x))
liftoff_gff['Length'] = liftoff_gff['End'] - liftoff_gff['Start'] + 1

In [46]:
H37Rv_gff.iloc[3861:3866]

,Chromosome,Source,FeatureType,Start,End,Score,Sense,Phase,Attributes,Length,RvID,GeneName
3861,Chromosome,RefSeq,gene,4272276,4273475,.,-,.,ID=gene-Rv3809c;Dbxref=GeneID:886142;Name=glf;...,1200,Rv3809c,glf
3862,Chromosome,RefSeq,gene,4273739,4274593,.,+,.,ID=gene-Rv3810;Dbxref=GeneID:886139;Name=pirG;...,855,Rv3810,pirG
3863,Chromosome,RefSeq,gene,4274798,4276417,.,+,.,ID=gene-Rv3811;Dbxref=GeneID:886137;Name=Rv381...,1620,Rv3811,Rv3811
3864,Chromosome,RefSeq,gene,4276571,4278085,.,+,.,ID=gene-Rv3812;Dbxref=GeneID:886143;Name=PE_PG...,1515,Rv3812,PE_PGRS62
3865,Chromosome,RefSeq,gene,4278394,4279215,.,-,.,ID=gene-Rv3813c;Dbxref=GeneID:886147;Name=Rv38...,822,Rv3813c,Rv3813c

In [49]:
personal_ref_dir

'/n/data1/hms/dbmi/farhat/Sanjana/TRUST_aln_personal_assembly'

In [ ]:
personal_ref_dir="/n/data1/hms/dbmi/farhat/Sanjana/TRUST_aln_personal_assembly"

# target.fa then query.fa
minimap2 -x asm5 -c --cs $personal_ref_dir/MFS-37/assembly/MFS-37.fasta $personal_ref_dir/MFS-38/assembly/MFS-38.fasta > $personal_ref_dir/MFS-37/assembly/MFS-38.to.MFS-37.paf

minimap2 -x asm5 -c --cs $personal_ref_dir/MFS-38/assembly/MFS-38.fasta $personal_ref_dir/MFS-37/assembly/MFS-37.fasta > $personal_ref_dir/MFS-38/assembly/MFS-37.to.MFS-38.paf

paftools.js liftover $personal_ref_dir/MFS-37/assembly/MFS-38.to.MFS-37.paf $personal_ref_dir/MFS-37/assembly/MFS-38_weird_regions.bed > $personal_ref_dir/MFS-37/assembly/MFS-38_weird_regions.MFS-37coords.bed

paftools.js liftover $personal_ref_dir/MFS-38/assembly/MFS-37.to.MFS-38.paf $personal_ref_dir/MFS-38/assembly/MFS-37_weird_regions.bed > $personal_ref_dir/MFS-38/assembly/MFS-37_weird_regions.MFS-38coords.bed

In [66]:
df_weird_region_MFS37 = pd.DataFrame(columns = ['BEG', 'CHROM', 'END'])
df_weird_region_MFS37.loc[0, :] = ['S0064-01_contig_1_pilon', 4287200-1, 4287400]
df_weird_region_MFS37.loc[1, :] = ['S0064-01_contig_1_pilon', 4289300-1, 4289700]

df_weird_region_MFS37.to_csv(f"{personal_ref_dir}/MFS-38/assembly/MFS-37_weird_regions.bed", sep='\t', header=None, index=False)

In [70]:
# df_weird_region_MFS37_MFS38coords = pd.read_csv(f"{personal_ref_dir}/MFS-38/assembly/MFS-37_weird_regions.MFS-38coords.bed", sep='\t', header=None)

In [73]:
df_weird_region_MFS37

                       BEG    CHROM      END
0  S0064-01_contig_1_pilon  4287199  4287400
1  S0064-01_contig_1_pilon  4289299  4289700

In [67]:
df_weird_region_MFS38 = pd.DataFrame(columns = ['BEG', 'CHROM', 'END'])
df_weird_region_MFS38.loc[0, :] = ['S0064-08_contig_1_pilon', 4286300-1, 4286900]

df_weird_region_MFS38.to_csv(f"{personal_ref_dir}/MFS-37/assembly/MFS-38_weird_regions.bed", sep='\t', header=None, index=False)

In [71]:
df_weird_region_MFS38_MFS37coords = pd.read_csv(f"{personal_ref_dir}/MFS-37/assembly/MFS-38_weird_regions.MFS-37coords.bed", sep='\t', header=None)

In [63]:
df_weird_region_MFS38

                       BEG    CHROM      END
0  S0064-08_contig_1_pilon  4286299  4286900

In [72]:
df_weird_region_MFS38_MFS37coords

,0,1,2,3,4,5
0,S0064-01_contig_1_pilon,4286300,4286452,S0064-08_contig_1_pilon_4286299_4286900_t3,0,+
1,S0064-01_contig_1_pilon,4290401,4290644,S0064-08_contig_1_pilon_4286299_4286900_t5,0,+

In [43]:
liftoff_gff.iloc[3834:3839]

,Chromosome,Source,FeatureType,Start,End,Score,Sense,Phase,Attributes,RvID,GeneName,Length
3834,S0064-01_contig_1_pilon,Liftoff,gene,4285036,4286235,.,-,.,ID=gene-Rv3809c;Dbxref=GeneID:886142;Name=glf;...,Rv3809c,glf,1200
3835,S0064-01_contig_1_pilon,Liftoff,gene,4286499,4287353,.,+,.,ID=gene-Rv3810;Dbxref=GeneID:886139;Name=pirG;...,Rv3810,pirG,855
3836,S0064-01_contig_1_pilon,Liftoff,gene,4287558,4289177,.,+,.,ID=gene-Rv3811;Dbxref=GeneID:886137;Name=Rv381...,Rv3811,Rv3811,1620
3837,S0064-01_contig_1_pilon,Liftoff,gene,4289331,4290845,.,+,.,ID=gene-Rv3812;Dbxref=GeneID:886143;Name=PE_PG...,Rv3812,PE_PGRS62,1515
3838,S0064-01_contig_1_pilon,Liftoff,gene,4291154,4291975,.,-,.,ID=gene-Rv3813c;Dbxref=GeneID:886147;Name=Rv38...,Rv3813c,Rv3813c,822

In [44]:
sample = 'MFS-38'
fName = f"{personal_ref_dir}/{sample}/assembly/H37Rv.liftoff.gff_polished"

liftoff_gff = pd.read_csv(fName,
                           sep='\t',
                           header=None,
                           comment='#',
                           names = ['Chromosome', 'Source', 'FeatureType', 'Start', 'End', 'Score', 'Sense', 'Phase', 'Attributes']
                          ).query("FeatureType=='gene'").reset_index(drop=True)


liftoff_gff['RvID'] = liftoff_gff['Attributes'].apply(lambda x: get_RvID_from_gff(x))
liftoff_gff['GeneName'] = liftoff_gff['Attributes'].apply(lambda x: get_geneName_from_gff(x))
liftoff_gff['Length'] = liftoff_gff['End'] - liftoff_gff['Start'] + 1

In [45]:
liftoff_gff.iloc[3834:3839]

,Chromosome,Source,FeatureType,Start,End,Score,Sense,Phase,Attributes,RvID,GeneName,Length
3834,S0064-08_contig_1_pilon,Liftoff,gene,4285035,4286234,.,-,.,ID=gene-Rv3809c;Dbxref=GeneID:886142;Name=glf;...,Rv3809c,glf,1200
3835,S0064-08_contig_1_pilon,Liftoff,gene,4285678,4287101,.,+,.,ID=gene-Rv3812;Dbxref=GeneID:886143;Name=PE_PG...,Rv3812,PE_PGRS62,1424
3836,S0064-08_contig_1_pilon,Liftoff,gene,4285695,4287305,.,-,.,ID=gene-Rv3811;Dbxref=GeneID:886137;Name=Rv381...,Rv3811,Rv3811,1611
3837,S0064-08_contig_1_pilon,Liftoff,gene,4287410,4288231,.,-,.,ID=gene-Rv3813c;Dbxref=GeneID:886147;Name=Rv38...,Rv3813c,Rv3813c,822
3838,S0064-08_contig_1_pilon,Liftoff,gene,4288246,4289031,.,-,.,ID=gene-Rv3814c;Dbxref=GeneID:886150;Name=Rv38...,Rv3814c,Rv3814c,786

In [68]:
sample = 'MFS-38'
df_depth = pd.read_csv(f"{personal_ref_dir}/{sample}/bam/{sample}.depth.tsv.gz", compression='gzip', header=None, sep='\t')

In [70]:
df_depth[2].median()

312.0

In [75]:
df_depth.loc[(df_depth[1] >= 4286400) & (df_depth[1] <= 4286700)][2].median()

121.0

In [61]:
len("GGGTCTTGCTGTGGTAAGTGTAGATGGCTTTGACTATGCCGGCGGACTCCAGCGGAGAGTAGTCGTTGCTCCCCGCGGTGTGGTGGACCACCGCGGCACGAACCCCCCTGTCGTACTCCGGTGTTTCGCATCGCAGTGACTCGTCTGCGC")

150

In [62]:
"GGGTCTTGCTGTGGTAAGTGTAGATGGCTTTGACTATGCCGGCGGACTCCAGCGGAGAGTAGTCGTTGCTCCCCGCGGTGTGGTGGACCACCGCGGCACGAACCCCCCTGTCGTACTCCGGTGTTTCGCATCGCAGTGACTCGTCTGCGC"

'GGGTCTTGCTGTGGTAAGTGTAGATGGCTTTGACTATGCCGGCGGACTCCAGCGGAGAGTAGTCGTTGCTCCCCGCGGTGTGGTGGACCACCGCGGCACGAACCCCCCTGTCGTACTCCGGTGTTTCGCATCGCAGTGACTCGTCTGCGC'

In [ ]:
'GCCGACCAGTGTGGTTGGCCGGAGGTCGTTTGGTCGCGATTGCCTCACGATTCGATATAACCACTCTAGTCACATCAACCACACTCGTACCATCGAGCGTGTGGGTTCATGCCATGCACTCGCGACCGCGGGAGCCGGCGAACCCGGCGC'

In [ ]:
blastx -query ./lowAF_variant_calling/test_BLAST.fasta -db ./lowAF_variant_calling/references/ref_genome/H37Rv_NC_000962.3.protein.BLAST.DB/database -evalue 1e-5 -outfmt "6 qseqid sseqid pident length qlen qstart qend sstart send evalue bitscore stitle" \
  -max_target_seqs 100 > ./lowAF_variant_calling/test_BLAST.protein.tsv

In [ ]:
blastn -query ./lowAF_variant_calling/test_BLAST.fasta -db ./lowAF_variant_calling/references/ref_genome/H37Rv_NC_000962.3.CDS.BLAST.DB/database -evalue 1e-5 -outfmt "6 qseqid sseqid pident length qlen qstart qend sstart send evalue bitscore stitle" \
  -max_target_seqs 100 > ./lowAF_variant_calling/test_BLAST.CDS.tsv

In [34]:
protein_BLAST_results = pd.read_csv("./lowAF_variant_calling/test_BLAST.protein.tsv",
                            sep='\t',
                            header=None
                           )

CDS_BLAST_results = pd.read_csv("./lowAF_variant_calling/test_BLAST.CDS.tsv",
                            sep='\t',
                            header=None
                           )

In [36]:
protein_BLAST_results

,0,1,2,3,4,5,6,7,8,9,10,11
0,MFS-38|VH00503:1:AAAVNHTM5:1:1202:76174:17433,lcl|NC_000962.3_prot_YP_178018.1_3793,100.0,49,150,148,2,206,254,1.380000e-28,102,lcl|NC_000962.3_prot_YP_178018.1_3793 [locus_t...

In [38]:
CDS_BLAST_results

,0,1,2,3,4,5,6,7,8,9,10,11
0,MFS-38|VH00503:1:AAAVNHTM5:1:1202:76174:17433,lcl|NC_000962.3_cds_YP_178018.1_3793,100.0,150,150,1,150,763,614,9.570000e-76,278,lcl|NC_000962.3_cds_YP_178018.1_3793 [locus_ta...
1,MFS-37|VH00503:1:AAAVNHTM5:1:2302:42961:47116,lcl|NC_000962.3_cds_NP_218327.1_3792,92.8,125,150,1,125,711,835,7.720000e-47,182,lcl|NC_000962.3_cds_NP_218327.1_3792 [gene=pir...

In [64]:
str(h37Rv_seq.seq[4274798-1:4276417])

'ATGGCAGCGACCGTCGTCATCGTCGCGTGGATAGCGAATCGTCCACCCGCCAGCTCCCATGAACCATCGCCGACGCCCAACACCCAGCTCGCCGAGCAGCCACTGATCGGGCTCGGCGGCGGCGTCACGGTACGCGAACTCACCCAGGACACACCGTTTTCATTGGTGGCGTTGACTGGCGACCTGGCCGGTACCTCCGCTCGTGTGCGCGCCAAGCGCCCGGACGGTGACTGGGGGCCGTGGTATCAGACCGAGTATGAAACCGAACCACGCGATCCGGCGGGCACCGACGGGTCCGTGGAACTTGGAGGACTCAATCCGGGTCCCCGTAGCACCGATCCGGTGTTCGTGGGCACCACCACCACCGTGCAGGTCGCGGTGACTCGCCCGATCGACGCACCGATAACTCAACCGCCGGCGGGGCGGCCGCCCAACGACTTGCTCGACAGCGGTTTGGGATACCGTCCAGCCACCAAGGAACAGCCATTCGGGCAGAACATCTCCGCGATCCTGATCTCGCCGCCGCAAGCGCCGCCCGGAACGCAGTGGACGCCACCAACCGCAGTCACCATGGCAGGCCAGCCGCCGGCCATCATCAGCCGGGCGGAATGGGGCGCAGACGAGTCACTGCGATGCGAAACACCGGAGTACGACAGGGGGGTTCGTGCCGCGGTGGTCCACCACACCGCGGGGAGCAACGACTACTCTCCGCTGGAGTCCGCCGGCATAGTCAAAGCCATCTACACTTACCACAGCAAGACCCTGGGCTGGTGTGACATCGCGTACAACGCCCTCGTCGACAAGTACGGCCAGGTGTTCGAGGGTAGCGCCGGCGGCCTCACCAAGCCGGTCGAAGGGTTCCACACCGGCGGATTCAACCGCAACACCTGGGGGGTTGCCATGATCGGCAACTTCGACGATGTGGCCCCCACGCCGATCCAGATCCGAACCGTCGGCCGGCTGCTCGGCTGGCGGCTGGGCATGGACGACGTCGATCCCAGGAGCATGGTGGATCTGCAGTCAGCGGGTAGCTCGTACACCACGTTTCCGGGTGGCGCCATAGCGCGATTGCCCGCCATCTTCACCCATCGCGACGTCGGCAACACCGACTGTCCGGGCAACGCCGCCTACGCTGTGATGGACGAGATCCGGGACATCGCAGCACATTTCAACGACCCGCCGGAGGAGCTGATCAAGGCGCTGGAAGGCGGCGCGATCTATCAGCGCTGGCAGGCGTTGGGCGGCATGAACAGCGCGCTGGGTGCACCGACCTCGCCGGAGGCCGACGCCGCGGATGGGGCGCGGTATGCAACCTTCGCTAAGGGCGCCATGTATTGGTCGCCGGTGACCGACGCTCAGCCGATCACGGGGGCAATCTATGAGGCCTGGGCTTCGCAGAGCTACGAACGCGGCCCGCTGGGACTGCCGACCAGCGCGGAGATCCAGGAGCCGCTGCAGATCACGCAGAACTTTCAACACGGAACCTTGAACTTCGAGCGCCTCACCGGCAATGTCACCGAAGTCGTCGACGGGATCACGACGCCACTGGCGACGCGGCCCCCGAGCGGCCCGACGGTGCCGCCCGAACACTTCACGCTGCCAACGCATCCGATCACCTGA'

In [47]:
df_hybrid_assemblies = pd.read_csv("./data/TRUST.PBAsm.ZA_106CI_AssemblySummary.csv")

In [48]:
df_hybrid_assemblies.query("SampleID in ['S0064-01', 'S0064-08']").T

                                             30             49
SampleID                               S0064-08       S0064-01
NumContigs                                    1              1
numContigs_Complete                           1              1
circContig_Length                       4420642        4424385
circContig_Cov                              118            109
Flye_EstimatedCov                           121            109
Flye_ReadLen_N50                          10914           8580
Flye_ReadLen_N90                           6133           4944
Lineage_Asm                        lineage2.2.1   lineage2.2.1
Lineage_AsmPP                      lineage2.2.1   lineage2.2.1
FlyeI3_dnaA_Found                          True           True
FlyeI3M_dnaA_Found                          NaN            NaN
FlyeI3MPP_dnaA_Found                        NaN            NaN
IlluminaCov_To_ONTAsm                       NaN            NaN
NumChanges_PilonPolished                      1              1
NumSNPs_PilonPolished                         0              0
NumTotalInsertions_PilonPolished              0              0
Num1bpInsertion_PilonPolished                 0              0
Num2bpInsertion_PilonPolished                 0              0
NumTotalDeletions_PilonPolished               1              1
Num1bpDeletion_PilonPolished                  0              1
PrimaryLineage_Asm                     lineage2       lineage2
Dataset_Tag                       TRUST_PB_Set4  TRUST_PB_Set2
PatientID                                 S0064          S0064
IsolateNum                                    8              1

In [ ]:
str(MFS_38[0][1][4286400-1:4286700])

In [47]:
str(MFS_38[0][1][4286300-1:4286900])

'CACTCGTACCATCGAGCGTGTGGGTTCATGCCATGCACTCGCGACCGCGGGATCTTGCTGTGGTAAGTGTAGATGGCTTTGACTATGCCGGCGGACTCCAGCGGAGAGTAGTCGTTGCTCCCCGCGGTGTGGTGGACCACCGCGGCACGAACCCCCCTGTCGTACTCCGGTGTTTCGCATCGCAGTGACTCGTCTGCGCCCCATTCCGCCCGGCTGATGATGGCCGGCGGCTGGCCTGCCATGGTGACTGCGGTTGGTGTGCCATTGGTGCTCACTTACGCCACATTGGGTGCGCCGTTCG'

In [37]:
sample = 'MFS-104'

df_lowAF_variants_personal_asm = pd.read_csv(f"{personal_ref_dir}/{sample}/freebayes/lowAF_variants.H37Rv.bed", 
                                             sep='\t', 
                                             header=None,
                                             usecols=[0, 1, 2, 3],
                                             names=['H37Rv_CHROM', 'H37Rv_BEG', 'H37Rv_END', 'Combined_Personal']
                                            )

df_lowAF_variants_personal_asm_personal_coords = pd.read_csv(f"{personal_ref_dir}/{sample}/freebayes/lowAF_variants.bed", sep='\t')

In [36]:
df_lowAF_variants_personal_asm

Empty DataFrame
Columns: [H37Rv_CHROM, H37Rv_BEG, H37Rv_END, Combined_Personal]
Index: []

In [38]:
df_lowAF_variants_personal_asm_personal_coords

Empty DataFrame
Columns: [CHROM, BEG, END, POS, REF, ALT, QUAL, FILTER, DP, RO, AO, AF, MQM, MQMR, SRF, SRR, SAF, SAR, SRP, SAP, RPP, RPPR, RPL, RPR, SAP_prob, SRP_prob]
Index: []

[0 rows x 26 columns]